# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4ff8f184fe5c8d3618a4d5dbe46da74571c434ebd87dff87476e8b25afce0c0f14220d220e96d8c1243326ab0da8379df8b3b176a87308ffd7e3ffee36e72b2

test:
  secret_key_base: 41409ad3483ef403bd10eaaef509f7ff50907c204334468177d600572db497c84dbf7171f4271c52bb5410c2f8c4c14a403b6c36ef8f94995271bd1ba8a43635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
